### PR TITLE
remove composer.lock

### PR DESCRIPTION
**Pull request by basz**
https://gist.github.com/basz/2575cdb5e6a0dd482ed19b2e4be02696

### CODE REVIEW

**Comment by heiglandreas** [comment]
@weierophinney Why is the composer.lock situation inconsistent between different zf-repos?

**Comment by Ocramius** [comment]
I think this is still undecided, so maybe we should clarify it once and for all in https://github.com/zendframework/maintainers/

As usual, I will add that I do not like having a lock file for very wobbly stuff anyway :-P It doesn't represent what end users will get anyway.

**Comment by basz** [comment]
Someone mentioned to me the lock files are there so travis can test lowest dependancies and such...

I haven't looked into how its done in zf repo's, but are you aware composer can install with a lowest flag...

no need for composer.lock files in this example  https://github.com/bushbaby/BsbFlysystem/blob/master/.travis.yml

**Comment by stefanotorresi** [comment]
this has been discussed in zendframework/zendframework#7660 and I'm currently working on making the presence of the lockfile consistent across all components.

the main reason behind this is to help contributors and mantainers.

**Comment by heiglandreas** [comment]
Thanks for raising the topic and causing some clarifications here @basz!

As already said by @stefanotorresi it's a wanted feature. And as it doesn't hurt anyone not wanting the composer.lock to run ```composer update``` instead of ```composer install``` it's not really an issue to have the file. So I'll close this PR.

**Pull request closed without merging**
