### PR TITLE
Fixes BC-Issue due to removed error-handler

### LINKED ISSUE #46: BC with default ErrorHandler
The default Error-Handler does not catch Errors.

Thanks to @sgehrig for mentioning and reaching out. A test for the problem can be found at https://gist.github.com/sgehrig/1e1cab662ed1d857b5a2895edc1e7730  though you might have to replace the ```"zendframework/zend-ldap" : "~2.7"``` with ```"zendframework/zend-ldap" : "2.7.0"``` to make this test succeed once the issue is fixed.

### PR DESCRIPTION
**Pull request by heiglandreas**
This PR fixes a BC-Issue caused by removing the Zend\StdLib\ErrorHandler and replacing it with a class that does nothing. Out of the Box that caused some functions to throw errors instead of the expected Exceptions.

The replacement-class for the Zend\StdLib\ErrorHandler now sets (and removes) an empty errorHandler.

Thanks to @sgehrig for mentioning and reaching out!

This fixes #46

### CODE REVIEW

**Comment by Ocramius** [comment]
@heiglandreas can you add a test case for this scenario? Something that triggers a notice would be OK, and just having the notice suppressed in the test would be sufficient, IMO

**Comment by heiglandreas** [comment]
In the bootstrap.php there is an ErrorHandler injected into the ErrorHandler. Due to that the issue didn't surface in the first place. I'll remove that line to make sure everything works out of the box. That should then be sufficient. Or don't you think?

**Comment by Ocramius** [comment]
@heiglandreas I mean a test specific for the ErrorHandler class

**Comment by heiglandreas** [comment]
Will do so ;)

**Pull request merged**
