### PR TITLE
Added an ldap_mod_del and ldap_mod_add functionality.

### PR DESCRIPTION
**Pull request by martinjinda**
This PR adds a way to delete or add one or more attributes to the
specified dn. 

This PR issue https://github.com/zendframework/zend-ldap/issues/5

### CODE REVIEW

**Comment by heiglandreas** [comment]
Thanks for your contribution! 

I'll review it as soon as I'm back from holiday (being sunday).

**Comment by martinjinda** [comment]
Yep, hope it'll be fine.

Enjoy vacation 👍

**Comment by ThaDafinser** [comment]
@martinjinda there is already a method `deleteAttributes()`
 https://github.com/zendframework/zend-ldap/blob/master/src/Ldap.php#L1314-L1339

Only the add method is missing or did i overseen something?

**Comment by martinjinda** [comment]
@ThaDafinser You didn't, but I did. So that's great. Plus I didn't control input from user in the entry at all.

**Comment by heiglandreas** [comment]
@martinjinda Thanks for your contribution. Can you please also add a test for the method?

**Comment by heiglandreas** [comment]
Damned Typo in a commit-message...

**Comment by heiglandreas** [comment]
@martinjinda Any news on this PR? I'D love to add it to the lib but I'd need some tests for that…

**Comment by martinjinda** [comment]
@heiglandreas Thanks for remind me. Will take a look.

**Pull request merged**
